[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "encoding"
    version = "1.3.0-SNAPSHOT"
    path = "../encoding-native/build/libs/encoding-native-1.3.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["encoding"]
